---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deprecate Chart

on:
  workflow_dispatch:
    inputs:
      chartName:
        type: string
        description: Chart Name (directory name under `apps/`)
        required: true
      reason:
        type: string
        description: Deprecation Reason
        required: true
      release:
        type: boolean
        description: Create Release
        default: true

jobs:
  plan:
    name: Plan (${{ inputs.chartName }})
    runs-on: ubuntu-latest
    outputs:
      pull-number: ${{ steps.pr.outputs.pull-request-number }}
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Generate Token
        uses: actions/create-github-app-token@7e473efe3cb98aa54f8d4bac15400b15fad77d94 # v2.2.0
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: Delete Chart
        run: |
          rm -rf ./apps/${{ inputs.chartName }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        id: pr
        with:
          body: |
            **Reason**: ${{ inputs.reason }}
          branch: deprecate/${{ inputs.chartName }}
          commit-message: "feat: deprecate ${{ inputs.chartName }}"
          sign-commits: true
          signoff: true
          title: "feat: deprecate ${{ inputs.chartName }}"
          token: ${{ steps.app-token.outputs.token }}

  merge:
    if: ${{ inputs.release }}
    name: Merge (${{ inputs.chartName }})
    needs: ["plan"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Generate Token
        uses: actions/create-github-app-token@7e473efe3cb98aa54f8d4bac15400b15fad77d94 # v2.2.0
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: Merge Pull Request
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ needs.plan.outputs.pull-number }},
              merge_method: 'squash',
            });

  announce:
    if: ${{ inputs.release }}
    name: Announce (${{ inputs.chartName }})
    needs: ["merge"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: false

      - name: Generate Token
        uses: actions/create-github-app-token@7e473efe3cb98aa54f8d4bac15400b15fad77d94 # v2.2.0
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: Get Release Tag
        uses: ./.github/actions/release-tag
        id: release
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Create Release
        uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1.20.0
        with:
          body: |
            > [!WARNING]
            > A chart has been deprecated and will no longer receive updates.
            > After **6 months** from now, its image will be **removed** from our container registry.

            ## ğŸ“¦ Chart

            **Name**: ${{ inputs.chartName }}
            **Reason**: ${{ inputs.reason }}
          tag: ${{ steps.release.outputs.tag }}
          token: ${{ steps.app-token.outputs.token }}
